In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
np.array([3, 4, 2.3, 3])

array([3. , 4. , 2.3, 3. ])

In [10]:
np.array([1,2,3,4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [12]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [18]:
a2 = np.array([[1,2,3],
               [4,5,6]])
type(a2)

numpy.ndarray

In [20]:
a2.shape

(2, 3)

In [21]:
a1.shape

(4,)

In [22]:
a2.ndim

2

In [23]:
a1.ndim

1

In [25]:
a2.dtype

dtype('int32')

In [29]:
a2.size

6

## Creating Numpy Arrays from Scratch

## zeros ones full arange linspace

In [36]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
np.ones([3,5], int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
np.arange(10,20,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
np.full((3,5), 9.6)

array([[9.6, 9.6, 9.6, 9.6, 9.6],
       [9.6, 9.6, 9.6, 9.6, 9.6],
       [9.6, 9.6, 9.6, 9.6, 9.6]])

In [46]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## random

In [59]:
# seed for reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [60]:
np.random.rand(4,4)

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [54]:
np.random.normal(0,1, (3,4)) #random cac gia tri trung binh 0 vo do lech chuan 1

array([[-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [57]:
np.random.randint(1, 8, (2,3))

array([[2, 4, 1],
       [6, 7, 1]])

## Array Indexing & Slicing
## one-dimensional subarray 


In [61]:
x1 = np.random.randint(20, size = 6)
x1

array([2, 0, 0, 4, 5, 6])

In [65]:
x1[4], x1[2], x1[1], x1[-1]

(5, 0, 0, 6)

## Multi_dimensional array

In [67]:
x2 = np.random.randint(10, size = (3,4))
x2

array([[8, 4, 1, 4],
       [9, 8, 1, 1],
       [7, 9, 9, 3]])

In [70]:
x2[1,2] = 6
x2

array([[8, 4, 1, 4],
       [9, 8, 6, 1],
       [7, 9, 9, 3]])

In [71]:
#Slicing x[start : stop : step]
x1

array([2, 0, 0, 4, 5, 6])

In [77]:
x1[::2]

array([2, 0, 5])

In [79]:
x2

array([[8, 4, 1, 4],
       [9, 8, 6, 1],
       [7, 9, 9, 3]])

In [80]:
x2[:2, :3]

array([[8, 4, 1],
       [9, 8, 6]])

In [81]:
x2[:, :2]

array([[8, 4],
       [9, 8],
       [7, 9]])

## Reshaping of array( chuyen doi sang dinh dang khac) & Transpose (chuyen vi)

In [84]:
grip = np.arange(1,10)
grip.shape

(9,)

In [85]:
grip.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
x = np.array([1,2,3])
x.shape

(3,)

In [88]:
x.reshape((1,3)).shape

(1, 3)

In [90]:
x = np.array([[1,2,3],
             [4,5,6]])
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Array Concatenation and Spliting (noi va tach array)

In [93]:
x = np.array([1,2,3])
y = np.array([5,8,9])

In [94]:
np.concatenate((x, y))

array([1, 2, 3, 5, 8, 9])

In [96]:
grip = np.array([[5,8,9,10], 
                [11,58,19,1]])
np.concatenate((grip, grip)) #axis = 0 by default

array([[ 5,  8,  9, 10],
       [11, 58, 19,  1],
       [ 5,  8,  9, 10],
       [11, 58, 19,  1]])

In [97]:
np.concatenate((grip, grip), axis = 1)

array([[ 5,  8,  9, 10,  5,  8,  9, 10],
       [11, 58, 19,  1, 11, 58, 19,  1]])

In [99]:
#vstack
x = np.array([1,2,3])
grip = np.array([[9,8,7],
                 [6,5,4]])
np.vstack((x, grip)) # noi theo column(cot)

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [100]:
#horizontally stack the arrays: hstack (noi theo chieu ngang rows)
y = np.array([[99], 
              [99]])
np.hstack((y, grip))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## Splitting of array

In [101]:
x = np.array([1,2,3,5,9,4,8,5,5,6,8,6,7])

In [105]:
x1, x2, x3 = np.split(x, [3,5])
x1, x2, x3

(array([1, 2, 3]), array([5, 9]), array([4, 8, 5, 5, 6, 8, 6, 7]))

## Broadcasting and Vectorized operations

In [6]:
a = np.arange(3)
a

array([0, 1, 2])

In [8]:
a + 5 # Broadcasting

array([5, 6, 7])

In [12]:
b = np.ones((3,3), int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
a.shape, b.shape

((3,), (3, 3))

In [14]:
a + b #broadcasting

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [15]:
a * b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

## Manipulate & compare Numpy Array

## Aggregation

In [16]:
list_number = [1,2,3]

In [17]:
ll = np.array(list_number)
ll

array([1, 2, 3])

In [18]:
sum(ll) #python sum()

6

In [19]:
np.sum(ll)

6